//Group list
export const FETCH_GROUPS = 'FETCH_GROUPS';
export const FETCH_GROUPS_PENDING = 'FETCH_GROUPS_PENDING';
export const FETCH_GROUPS_FULFILLED = 'FETCH_GROUPS_FULFILLED';
export const FETCH_GROUPS_REJECTED = 'FETCH_GROUPS_REJECTED';

// Group create
export const ADD_GROUP = 'ADD_GROUP';
export const EDIT_GROUP = 'EDIT_GROUP';
export const ADD_GROUP_FULFILLED = 'ADD_GROUP_FULFILLED';
export const ADD_GROUP_REJECTED = 'ADD_GROUP_REJECTED';

// Group update
export const UPDATE_GROUP = 'UPDATE_GROUP';
export const UPDATE_GROUP_FULFILLED = 'UPDATE_GROUP_FULFILLED';
export const UPDATE_GROUP_REJECTED = 'UPDATE_GROUP_REJECTED';

// Group delete
export const DELETE_GROUP = 'DELETE_GROUP';
export const DELETE_GROUP_FULFILLED = 'DELETE_GROUP_FULFILLED';
export const DELETE_GROUP_REJECTED = 'DELETE_GROUP_REJECTED';

// Select group
export const SELECT_GROUP = 'SELECT_GROUP';
export const RESET_SELECT_GROUP = 'RESET_SELECT_GROUP';

export const SHOW_GROUP_MODAL_FORM = 'SHOW_GROUP_MODAL_FORM';
